### ISSUE TITLE
TypeError: an integer is required (got type tuple)

### ISSUE THREAD

**Issue by AkkuAg** [arccoder/opencvdragrect#2]

**Comment by darkprince1337** [comment]
Did your problem solved?

**Comment by AkkuAg** [comment]
> Did your problem solved?

Yes. Typecasted the values to integer

**Comment by darkprince1337** [comment]
Can you tell me where exactly?
or Can you please upload the updated `selectinWindow.py`?

**Comment by AkkuAg** [comment]
> Can you tell me where exactly?
> or Can you please upload the updated `selectinWindow.py`?
in drawSelectMarkers for top left
` cv2.rectangle(image, (int(dragObj.outRect.x - dragObj.sBlk),
                          int(dragObj.outRect.y - dragObj.sBlk)),
                  (int(dragObj.outRect.x - dragObj.sBlk + dragObj.sBlk * 2),
                   int(dragObj.outRect.y - dragObj.sBlk + dragObj.sBlk * 2)),
                  (0, 255, 0), 2)`
Similarly for all others it needs to be done in drawSelectMarkers

**Comment by darkprince1337** [comment]
> > Can you tell me where exactly?
> > or Can you please upload the updated `selectinWindow.py`?
> > in drawSelectMarkers for top left
> > ` cv2.rectangle(image, (int(dragObj.outRect.x - dragObj.sBlk),                           int(dragObj.outRect.y - dragObj.sBlk)),                   (int(dragObj.outRect.x - dragObj.sBlk + dragObj.sBlk * 2),                    int(dragObj.outRect.y - dragObj.sBlk + dragObj.sBlk * 2)),                   (0, 255, 0), 2)`
> > Similarly for all others it needs to be done in drawSelectMarkers

Damn! that's time consuming. Can you please share your updated `selectinWindow.py` file?

**Comment by AkkuAg** [comment]
[selectinwindow.txt](https://github.com/arccoder/opencvdragrect/files/3349325/selectinwindow.txt)

**Comment by darkprince1337** [comment]
> [selectinwindow.txt](https://github.com/arccoder/opencvdragrect/files/3349325/selectinwindow.txt)

Thanks a lot man!

**Comment by sureshsass** [comment]
The program crashes after some time while trying to resize or move the rectangle Using the script example provided. Any way this can be solved
