### ISSUE TITLE
What version of OpenCV is this written in?

### ISSUE THREAD

**Issue by JulianPitney** [arccoder/opencvdragrect#5]
What version of OpenCV is this written in?

**Comment by arccoder** [comment]
Earlier it was using OpenCV 3.1.
As of today's commit d56ac9c4ab50ff46ecbac35fd2784f042f3014f1 I tested with 4.5.1.
However, the functionality used from OpenCV is not new and has been around OpenCV 2+.
So you should be good to use it with any OpenCV version.
