### ISSUE TITLE
Rotated rectangle 

### ISSUE THREAD

**Issue by aladinbrahem** [arccoder/opencvdragrect#6]
Is possible to make the rectangle rotated ! 
If possible can you help me.

**Comment by arccoder** [comment]
Hi @aladinbrahem,
This project is limited to dragging a single rectangle on an image.
I don't have any plans to add support for rotated rectangles.
Thanks,
@arccoder

**Comment by aladinbrahem** [comment]
Thank you for your response !

We do it 👏
