### ISSUE TITLE
How to draw multiple rectangles in the same image?

### ISSUE THREAD

**Issue by nithinreddyy** [arccoder/opencvdragrect#7]
I'm unable to draw multiple rectangles in the same image. Can anyone help me with this?

**Comment by arccoder** [comment]
Hi @nithinreddyy,
This project is limited to dragging a single rectangle on an image.
I don't have any plans to add support for multiple rectangles.
Thanks,
@arccoder

**Comment by JohnTailor** [comment]
You can draw multiple ones, but only the last one will be shown as follows:
Define a global var:
drageRects=[]

In Function  def dragrect(event, x, y, flags, dragObj) add:

    if event == cv2.EVENT_RBUTTONDOWN:
        drageRects.append(copy.deepcopy(dragObj))
        dragObj.reset()
        print("Reset",len(drageRects))
        mouseUp(dragObj)

Add the function reset to Dragrectangle:
    def reset(self):
        # Set rect to zero width and height
        self.outRect.x = 0
        self.outRect.y = 0
        self.outRect.w = 0
        self.outRect.h = 0
        self.active =  0

Now, whenever you rightclick the current rectangle is added to the list of drageRects and you can start drawing a new one.
